[opendum]
family = "OpenAI"
providers = ["ollama_cloud", "openrouter", "workers_ai"]

[ollama_cloud]
upstream = "gpt-oss:120b"

[openrouter]
upstream = "openai/gpt-oss-120b:free"

[workers_ai]
upstream = "@cf/openai/gpt-oss-120b"