release_date = "2024-12"
knowledge = "2024-10"
reasoning = true
tool_call = true
attachment = true

[cost]
input = 0.2
output = 0.6

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text","image"]
output = ["text"]

[opendum]
family = "NVIDIA"
providers = ["openrouter"]

[opendum.upstream]
openrouter = "nvidia/nemotron-nano-12b-v2-vl:free"
