// Nvidia API constants

export const NVIDIA_NIM_API_BASE_URL = "https://integrate.api.nvidia.com/v1";

export const NVIDIA_NIM_SUPPORTED_PARAMS = new Set([
  "model",
  "messages",
  "temperature",
  "top_p",
  "max_tokens",
  "stream",
  "tools",
  "tool_choice",
  "presence_penalty",
  "frequency_penalty",
  "n",
  "stop",
  "seed",
  "response_format",
]);

export const NVIDIA_NIM_MODEL_MAP: Record<string, string> = {
  "deepseek-ai-deepseek-coder-6.7b-instruct": "deepseek-ai/deepseek-coder-6.7b-instruct",
  "deepseek-ai-deepseek-r1": "deepseek-ai/deepseek-r1",
  "deepseek-ai-deepseek-r1-0528": "deepseek-ai/deepseek-r1-0528",
  "deepseek-ai-deepseek-v3.1-terminus": "deepseek-ai/deepseek-v3.1-terminus",
  "deepseek-v3.1": "deepseek-ai/deepseek-v3.1",
  "deepseek-v3.2": "deepseek-ai/deepseek-v3.2",
  "devstral-2-123b": "mistralai/devstral-2-123b-instruct-2512",
  "gemma3-12b": "google/gemma-3-12b-it",
  "gemma3-27b": "google/gemma-3-27b-it",
  "glm-4.7": "z-ai/glm4.7",
  "google-codegemma-1.1-7b": "google/codegemma-1.1-7b",
  "google-codegemma-7b": "google/codegemma-7b",
  "google-gemma-2-27b-it": "google/gemma-2-27b-it",
  "google-gemma-2-2b-it": "google/gemma-2-2b-it",
  "google-gemma-3-1b-it": "google/gemma-3-1b-it",
  "google-gemma-3n-e2b-it": "google/gemma-3n-e2b-it",
  "google-gemma-3n-e4b-it": "google/gemma-3n-e4b-it",
  "gpt-oss-120b-medium": "openai/gpt-oss-120b",
  "kimi-k2": "moonshotai/kimi-k2-instruct",
  "kimi-k2-0905": "moonshotai/kimi-k2-instruct-0905",
  "kimi-k2-thinking": "moonshotai/kimi-k2-thinking",
  "kimi-k2.5": "moonshotai/kimi-k2.5",
  "meta-codellama-70b": "meta/codellama-70b",
  "meta-llama-3.1-405b-instruct": "meta/llama-3.1-405b-instruct",
  "meta-llama-3.2-11b-vision-instruct": "meta/llama-3.2-11b-vision-instruct",
  "meta-llama-3.2-1b-instruct": "meta/llama-3.2-1b-instruct",
  "meta-llama-3.3-70b-instruct": "meta/llama-3.3-70b-instruct",
  "meta-llama-4-maverick-17b-128e-instruct": "meta/llama-4-maverick-17b-128e-instruct",
  "meta-llama-4-scout-17b-16e-instruct": "meta/llama-4-scout-17b-16e-instruct",
  "meta-llama3-70b-instruct": "meta/llama3-70b-instruct",
  "meta-llama3-8b-instruct": "meta/llama3-8b-instruct",
  "microsoft-phi-3-medium-128k-instruct": "microsoft/phi-3-medium-128k-instruct",
  "microsoft-phi-3-medium-4k-instruct": "microsoft/phi-3-medium-4k-instruct",
  "microsoft-phi-3-small-128k-instruct": "microsoft/phi-3-small-128k-instruct",
  "microsoft-phi-3-small-8k-instruct": "microsoft/phi-3-small-8k-instruct",
  "microsoft-phi-3-vision-128k-instruct": "microsoft/phi-3-vision-128k-instruct",
  "microsoft-phi-3.5-moe-instruct": "microsoft/phi-3.5-moe-instruct",
  "microsoft-phi-3.5-vision-instruct": "microsoft/phi-3.5-vision-instruct",
  "microsoft-phi-4-mini-instruct": "microsoft/phi-4-mini-instruct",
  "minimax-m2": "minimaxai/minimax-m2",
  "minimax-m2.1": "minimaxai/minimax-m2.1",
  "ministral-3-14b": "mistralai/ministral-14b-instruct-2512",
  "mistral-large-3-675b": "mistralai/mistral-large-3-675b-instruct-2512",
  "mistralai-codestral-22b-instruct-v0.1": "mistralai/codestral-22b-instruct-v0.1",
  "mistralai-mamba-codestral-7b-v0.1": "mistralai/mamba-codestral-7b-v0.1",
  "mistralai-mistral-large-2-instruct": "mistralai/mistral-large-2-instruct",
  "mistralai-mistral-small-3.1-24b-instruct-2503": "mistralai/mistral-small-3.1-24b-instruct-2503",
  "nemotron-3-nano-30b": "nvidia/nemotron-3-nano-30b-a3b",
  "nim-llama-3.1-70b-instruct": "meta/llama-3.1-70b-instruct",
  "nvidia-cosmos-nemotron-34b": "nvidia/cosmos-nemotron-34b",
  "nvidia-llama-3.1-nemotron-51b-instruct": "nvidia/llama-3.1-nemotron-51b-instruct",
  "nvidia-llama-3.1-nemotron-70b-instruct": "nvidia/llama-3.1-nemotron-70b-instruct",
  "nvidia-llama-3.1-nemotron-ultra-253b-v1": "nvidia/llama-3.1-nemotron-ultra-253b-v1",
  "nvidia-llama-3.3-nemotron-super-49b-v1": "nvidia/llama-3.3-nemotron-super-49b-v1",
  "nvidia-llama-3.3-nemotron-super-49b-v1.5": "nvidia/llama-3.3-nemotron-super-49b-v1.5",
  "nvidia-llama3-chatqa-1.5-70b": "nvidia/llama3-chatqa-1.5-70b",
  "nvidia-nemotron-4-340b-instruct": "nvidia/nemotron-4-340b-instruct",
  "nvidia-nvidia-nemotron-nano-9b-v2": "nvidia/nvidia-nemotron-nano-9b-v2",
  "qwen-qwen2.5-coder-32b-instruct": "qwen/qwen2.5-coder-32b-instruct",
  "qwen-qwen2.5-coder-7b-instruct": "qwen/qwen2.5-coder-7b-instruct",
  "qwen-qwen3-235b-a22b": "qwen/qwen3-235b-a22b",
  "qwen-qwen3-next-80b-a3b-instruct": "qwen/qwen3-next-80b-a3b-instruct",
  "qwen-qwq-32b": "qwen/qwq-32b",
  "qwen3-coder-480b": "qwen/qwen3-coder-480b-a35b-instruct",
  "qwen3-next-80b": "qwen/qwen3-next-80b-a3b-thinking",
};

export const NVIDIA_NIM_MODELS = new Set(Object.keys(NVIDIA_NIM_MODEL_MAP));
