// Nvidia API constants

export const NVIDIA_NIM_API_BASE_URL = "https://integrate.api.nvidia.com/v1";

export const NVIDIA_NIM_SUPPORTED_PARAMS = new Set([
  "model",
  "messages",
  "temperature",
  "top_p",
  "max_tokens",
  "stream",
  "tools",
  "tool_choice",
  "presence_penalty",
  "frequency_penalty",
  "n",
  "stop",
  "seed",
  "response_format",
]);

export const NVIDIA_NIM_MODEL_MAP: Record<string, string> = {
  "abacusai-dracarys-llama-3.1-70b-instruct": "abacusai/dracarys-llama-3.1-70b-instruct",
  "ai21labs-jamba-1.5-large-instruct": "ai21labs/jamba-1.5-large-instruct",
  "ai21labs-jamba-1.5-mini-instruct": "ai21labs/jamba-1.5-mini-instruct",
  "aisingapore-sea-lion-7b-instruct": "aisingapore/sea-lion-7b-instruct",
  "baichuan-inc-baichuan2-13b-chat": "baichuan-inc/baichuan2-13b-chat",
  "bytedance-seed-oss-36b-instruct": "bytedance/seed-oss-36b-instruct",
  "databricks-dbrx-instruct": "databricks/dbrx-instruct",
  "deepseek-ai-deepseek-coder-6.7b-instruct": "deepseek-ai/deepseek-coder-6.7b-instruct",
  "deepseek-ai-deepseek-v3.1-terminus": "deepseek-ai/deepseek-v3.1-terminus",
  "deepseek-v3.1": "deepseek-ai/deepseek-v3.1",
  "deepseek-v3.2": "deepseek-ai/deepseek-v3.2",
  "devstral-2-123b": "mistralai/devstral-2-123b-instruct-2512",
  "gemma3-12b": "google/gemma-3-12b-it",
  "gemma3-27b": "google/gemma-3-27b-it",
  "glm-4.7": "z-ai/glm4.7",
  "google-codegemma-1.1-7b": "google/codegemma-1.1-7b",
  "google-codegemma-7b": "google/codegemma-7b",
  "google-gemma-2-27b-it": "google/gemma-2-27b-it",
  "google-gemma-2-2b-it": "google/gemma-2-2b-it",
  "google-gemma-2-9b-it": "google/gemma-2-9b-it",
  "google-gemma-3-1b-it": "google/gemma-3-1b-it",
  "google-gemma-3-4b-it": "google/gemma-3-4b-it",
  "google-gemma-3n-e2b-it": "google/gemma-3n-e2b-it",
  "google-gemma-3n-e4b-it": "google/gemma-3n-e4b-it",
  "gotocompany-gemma-2-9b-cpt-sahabatai-instruct": "gotocompany/gemma-2-9b-cpt-sahabatai-instruct",
  "gpt-oss-120b-medium": "openai/gpt-oss-120b",
  "ibm-granite-3.0-3b-a800m-instruct": "ibm/granite-3.0-3b-a800m-instruct",
  "ibm-granite-3.0-8b-instruct": "ibm/granite-3.0-8b-instruct",
  "ibm-granite-3.3-8b-instruct": "ibm/granite-3.3-8b-instruct",
  "ibm-granite-34b-code-instruct": "ibm/granite-34b-code-instruct",
  "ibm-granite-8b-code-instruct": "ibm/granite-8b-code-instruct",
  "institute-of-science-tokyo-llama-3.1-swallow-70b-instruct-v0.1": "institute-of-science-tokyo/llama-3.1-swallow-70b-instruct-v0.1",
  "institute-of-science-tokyo-llama-3.1-swallow-8b-instruct-v0.1": "institute-of-science-tokyo/llama-3.1-swallow-8b-instruct-v0.1",
  "kimi-k2": "moonshotai/kimi-k2-instruct",
  "kimi-k2-0905": "moonshotai/kimi-k2-instruct-0905",
  "kimi-k2-thinking": "moonshotai/kimi-k2-thinking",
  "kimi-k2.5": "moonshotai/kimi-k2.5",
  "marin-marin-8b-instruct": "marin/marin-8b-instruct",
  "mediatek-breeze-7b-instruct": "mediatek/breeze-7b-instruct",
  "meta-codellama-70b": "meta/codellama-70b",
  "meta-llama-3.1-405b-instruct": "meta/llama-3.1-405b-instruct",
  "meta-llama-3.1-8b-instruct": "meta/llama-3.1-8b-instruct",
  "meta-llama-3.2-11b-vision-instruct": "meta/llama-3.2-11b-vision-instruct",
  "meta-llama-3.2-1b-instruct": "meta/llama-3.2-1b-instruct",
  "meta-llama-3.2-3b-instruct": "meta/llama-3.2-3b-instruct",
  "meta-llama-3.2-90b-vision-instruct": "meta/llama-3.2-90b-vision-instruct",
  "meta-llama-3.3-70b-instruct": "meta/llama-3.3-70b-instruct",
  "meta-llama-4-maverick-17b-128e-instruct": "meta/llama-4-maverick-17b-128e-instruct",
  "meta-llama-4-scout-17b-16e-instruct": "meta/llama-4-scout-17b-16e-instruct",
  "meta-llama3-70b-instruct": "meta/llama3-70b-instruct",
  "meta-llama3-8b-instruct": "meta/llama3-8b-instruct",
  "microsoft-phi-3-medium-128k-instruct": "microsoft/phi-3-medium-128k-instruct",
  "microsoft-phi-3-medium-4k-instruct": "microsoft/phi-3-medium-4k-instruct",
  "microsoft-phi-3-mini-128k-instruct": "microsoft/phi-3-mini-128k-instruct",
  "microsoft-phi-3-mini-4k-instruct": "microsoft/phi-3-mini-4k-instruct",
  "microsoft-phi-3-small-128k-instruct": "microsoft/phi-3-small-128k-instruct",
  "microsoft-phi-3-small-8k-instruct": "microsoft/phi-3-small-8k-instruct",
  "microsoft-phi-3-vision-128k-instruct": "microsoft/phi-3-vision-128k-instruct",
  "microsoft-phi-3.5-mini-instruct": "microsoft/phi-3.5-mini-instruct",
  "microsoft-phi-3.5-moe-instruct": "microsoft/phi-3.5-moe-instruct",
  "microsoft-phi-3.5-vision-instruct": "microsoft/phi-3.5-vision-instruct",
  "microsoft-phi-4-mini-instruct": "microsoft/phi-4-mini-instruct",
  "microsoft-phi-4-multimodal-instruct": "microsoft/phi-4-multimodal-instruct",
  "minimax-m2": "minimaxai/minimax-m2",
  "minimax-m2.1": "minimaxai/minimax-m2.1",
  "ministral-3-14b": "mistralai/ministral-14b-instruct-2512",
  "mistral-large-3-675b": "mistralai/mistral-large-3-675b-instruct-2512",
  "mistralai-codestral-22b-instruct-v0.1": "mistralai/codestral-22b-instruct-v0.1",
  "mistralai-magistral-small-2506": "mistralai/magistral-small-2506",
  "mistralai-mamba-codestral-7b-v0.1": "mistralai/mamba-codestral-7b-v0.1",
  "mistralai-mistral-7b-instruct-v0.2": "mistralai/mistral-7b-instruct-v0.2",
  "mistralai-mistral-7b-instruct-v0.3": "mistralai/mistral-7b-instruct-v0.3",
  "mistralai-mistral-large": "mistralai/mistral-large",
  "mistralai-mistral-large-2-instruct": "mistralai/mistral-large-2-instruct",
  "mistralai-mistral-medium-3-instruct": "mistralai/mistral-medium-3-instruct",
  "mistralai-mistral-nemotron": "mistralai/mistral-nemotron",
  "mistralai-mistral-small-24b-instruct": "mistralai/mistral-small-24b-instruct",
  "mistralai-mistral-small-3.1-24b-instruct-2503": "mistralai/mistral-small-3.1-24b-instruct-2503",
  "mistralai-mixtral-8x22b-instruct-v0.1": "mistralai/mixtral-8x22b-instruct-v0.1",
  "mistralai-mixtral-8x7b-instruct-v0.1": "mistralai/mixtral-8x7b-instruct-v0.1",
  "nemotron-3-nano-30b": "nvidia/nemotron-3-nano-30b-a3b",
  "nim-llama-3.1-70b-instruct": "meta/llama-3.1-70b-instruct",
  "nv-mistralai-mistral-nemo-12b-instruct": "nv-mistralai/mistral-nemo-12b-instruct",
  "nvidia-cosmos-reason2-8b": "nvidia/cosmos-reason2-8b",
  "nvidia-llama-3.1-nemotron-51b-instruct": "nvidia/llama-3.1-nemotron-51b-instruct",
  "nvidia-llama-3.1-nemotron-70b-instruct": "nvidia/llama-3.1-nemotron-70b-instruct",
  "nvidia-llama-3.1-nemotron-ultra-253b-v1": "nvidia/llama-3.1-nemotron-ultra-253b-v1",
  "nvidia-llama-3.3-nemotron-super-49b-v1": "nvidia/llama-3.3-nemotron-super-49b-v1",
  "nvidia-llama-3.3-nemotron-super-49b-v1.5": "nvidia/llama-3.3-nemotron-super-49b-v1.5",
  "nvidia-llama3-chatqa-1.5-70b": "nvidia/llama3-chatqa-1.5-70b",
  "nvidia-mistral-nemo-minitron-8b-8k-instruct": "nvidia/mistral-nemo-minitron-8b-8k-instruct",
  "nvidia-nemotron-4-340b-instruct": "nvidia/nemotron-4-340b-instruct",
  "nvidia-nemotron-4-mini-hindi-4b-instruct": "nvidia/nemotron-4-mini-hindi-4b-instruct",
  "nvidia-nemotron-mini-4b-instruct": "nvidia/nemotron-mini-4b-instruct",
  "nvidia-nvidia-nemotron-nano-9b-v2": "nvidia/nvidia-nemotron-nano-9b-v2",
  "nvidia-usdcode-llama-3.1-70b-instruct": "nvidia/usdcode-llama-3.1-70b-instruct",
  "openai-gpt-oss-20b": "openai/gpt-oss-20b",
  "opengpt-x-teuken-7b-instruct-commercial-v0.4": "opengpt-x/teuken-7b-instruct-commercial-v0.4",
  "qwen-qwen2-7b-instruct": "qwen/qwen2-7b-instruct",
  "qwen-qwen2.5-7b-instruct": "qwen/qwen2.5-7b-instruct",
  "qwen-qwen2.5-coder-32b-instruct": "qwen/qwen2.5-coder-32b-instruct",
  "qwen-qwen2.5-coder-7b-instruct": "qwen/qwen2.5-coder-7b-instruct",
  "qwen-qwen3-235b-a22b": "qwen/qwen3-235b-a22b",
  "qwen-qwen3-next-80b-a3b-instruct": "qwen/qwen3-next-80b-a3b-instruct",
  "qwen-qwq-32b": "qwen/qwq-32b",
  "qwen3-coder-480b": "qwen/qwen3-coder-480b-a35b-instruct",
  "qwen3-next-80b": "qwen/qwen3-next-80b-a3b-thinking",
  "rakuten-rakutenai-7b-chat": "rakuten/rakutenai-7b-chat",
  "rakuten-rakutenai-7b-instruct": "rakuten/rakutenai-7b-instruct",
  "speakleash-bielik-11b-v2.3-instruct": "speakleash/bielik-11b-v2.3-instruct",
  "speakleash-bielik-11b-v2.6-instruct": "speakleash/bielik-11b-v2.6-instruct",
  "stockmark-stockmark-2-100b-instruct": "stockmark/stockmark-2-100b-instruct",
  "tiiuae-falcon3-7b-instruct": "tiiuae/falcon3-7b-instruct",
  "tokyotech-llm-llama-3-swallow-70b-instruct-v0.1": "tokyotech-llm/llama-3-swallow-70b-instruct-v0.1",
  "upstage-solar-10.7b-instruct": "upstage/solar-10.7b-instruct",
  "utter-project-eurollm-9b-instruct": "utter-project/eurollm-9b-instruct",
  "yentinglin-llama-3-taiwan-70b-instruct": "yentinglin/llama-3-taiwan-70b-instruct",
  "zyphra-zamba2-7b-instruct": "zyphra/zamba2-7b-instruct",
};

export const NVIDIA_NIM_MODELS = new Set(Object.keys(NVIDIA_NIM_MODEL_MAP));
