release_date = "2025-09-23"
knowledge = "2025-04"
reasoning = true
tool_call = true
attachment = false

[cost]
input = 0.2
output = 1.6

[limit]
context = 262_144
output = 32_768

[modalities]
input = ["text","image"]
output = ["text"]

[opendum]
family = "Qwen"
providers = ["iflow"]
