release_date = "2025-08-05"
reasoning = false
tool_call = true
attachment = true

[cost]
input = 1.01
output = 1.01

[limit]
context = 128_000
output = 8_192

[modalities]
input = ["text","image","audio","video"]
output = ["text"]

[opendum]
family = "Qwen"
providers = ["iflow"]
