release_date = "2026-02-16"
knowledge = "2025-04"
reasoning = true
tool_call = true
attachment = false

[cost]
input = 0.573
output = 3.44

[limit]
context = 1_000_000
output = 65_536

[modalities]
input = ["text","image","video"]
output = ["text"]

[opendum]
family = "Qwen"
providers = ["iflow", "qwen_code"]

[opendum.upstream]
qwen_code = "coder-model"
