release_date = "2024-05-29"
reasoning = false
tool_call = true
attachment = false

[limit]
context = 128_000
output = 4_096

[modalities]
input = ["text"]
output = ["text"]

[opendum]
family = "Mistral"
providers = ["nvidia_nim"]
aliases = ["mistralai-codestral-22b-instruct-v0.1", "mistralai/codestral-22b-instruct-v0.1"]

[opendum.upstream]
nvidia_nim = "mistralai/codestral-22b-instruct-v0.1"
