release_date = "2025-06-20"
knowledge = "2025-03"
reasoning = false
tool_call = true
attachment = false

[cost]
input = 0.1
output = 0.3

[limit]
context = 128_000
output = 16_384

[modalities]
input = ["text","image"]
output = ["text"]

[opendum]
family = "Mistral"
providers = []
