release_date = "2025-09-04"
reasoning = false
tool_call = true
attachment = false

[limit]
context = 262_000
output = 262_000

[modalities]
input = ["text"]
output = ["text"]

[opendum]
family = "ByteDance"
providers = ["nvidia_nim"]

[nvidia_nim]
upstream = "bytedance/seed-oss-36b-instruct"