/**
 * Ignored models list.
 *
 * Models in this set are filtered out from the effective model registry
 * and will not appear in model listings, API responses, or UI.
 * They are NOT deleted from provider constants — only hidden.
 *
 * To un-ignore a model, simply remove it from this set.
 */
export const IGNORED_MODELS = new Set([
  // ===== Internal / Generic =====
  "iflow-rome-30ba3b",

  // ===== Old / Small / Regional — NVIDIA NIM =====
  "baichuan2-13b-chat",
  "bielik-11b-v2.3-instruct",
  "bielik-11b-v2.6-instruct",
  "breeze-7b-instruct",
  "codegemma-1.1-7b",
  "codegemma-7b",
  "codellama-70b",
  "cosmos-reason2-8b",
  "dbrx-instruct",
  "deepseek-coder-6.7b-instruct",
  "dracarys-llama-3.1-70b-instruct",
  "eurollm-9b-instruct",
  "falcon3-7b-instruct",
  "gemma-2-27b-it",
  "gemma-2-2b-it",
  "gemma-2-9b-cpt-sahabatai-instruct",
  "gemma-2-9b-it",
  "gemma-3-1b-it",
  "gemma-3-4b-it",
  "gemma-3n-e2b-it",
  "gemma-3n-e4b-it",
  "granite-3.0-3b-a800m-instruct",
  "granite-3.0-8b-instruct",
  "granite-3.3-8b-instruct",
  "granite-34b-code-instruct",
  "granite-8b-code-instruct",
  "jamba-1.5-large-instruct",
  "jamba-1.5-mini-instruct",
  "llama-3-swallow-70b-instruct-v0.1",
  "llama-3-taiwan-70b-instruct",
  "llama-3.1-8b-instruct",
  "llama-3.1-nemotron-51b-instruct",
  "llama-3.1-nemotron-70b-instruct",
  "llama-3.1-swallow-70b-instruct-v0.1",
  "llama-3.1-swallow-8b-instruct-v0.1",
  "llama-3.2-11b-vision-instruct",
  "llama-3.2-1b-instruct",
  "llama-3.2-3b-instruct",
  "llama-3.2-90b-vision-instruct",
  "llama-3.3-nemotron-super-49b-v1",
  "llama-3.3-nemotron-super-49b-v1.5",
  "llama3-70b-instruct",
  "llama3-8b-instruct",
  "llama3-chatqa-1.5-70b",
  "mamba-codestral-7b-v0.1",
  "marin-8b-instruct",
  "ministral-3-14b",
  "mistral-7b-instruct-v0.2",
  "mistral-7b-instruct-v0.3",
  "mistral-large",
  "mistral-large-2-instruct",
  "mistral-medium-3-instruct",
  "mistral-nemo-12b-instruct",
  "mistral-nemo-minitron-8b-8k-instruct",
  "mistral-small-24b-instruct",
  "mistral-small-3.1-24b-instruct-2503",
  "mixtral-8x22b-instruct-v0.1",
  "mixtral-8x7b-instruct-v0.1",
  "nemotron-4-340b-instruct",
  "nemotron-4-mini-hindi-4b-instruct",
  "nemotron-mini-4b-instruct",
  "nemotron-nano-9b-v2",
  "nim-llama-3.1-70b-instruct",
  "phi-3-medium-128k-instruct",
  "phi-3-medium-4k-instruct",
  "phi-3-mini-128k-instruct",
  "phi-3-mini-4k-instruct",
  "phi-3-small-128k-instruct",
  "phi-3-small-8k-instruct",
  "phi-3-vision-128k-instruct",
  "phi-3.5-mini-instruct",
  "phi-3.5-moe-instruct",
  "phi-3.5-vision-instruct",
  "qwen2-7b-instruct",
  "qwen2.5-7b-instruct",
  "qwen2.5-coder-7b",
  "qwq-32b",
  "rakutenai-7b-chat",
  "rakutenai-7b-instruct",
  "sea-lion-7b-instruct",
  "seed-oss-36b-instruct",
  "solar-10.7b-instruct",
  "stockmark-2-100b-instruct",
  "teuken-7b-instruct-commercial-v0.4",
  "usdcode-llama-3.1-70b-instruct",
  "zamba2-7b-instruct",

  // ===== Niche / Small — Ollama Cloud =====
  "cogito-2.1-671b",
  "devstral-small-2-24b",
  "gemma3-4b",
  "ministral-3-3b",
  "ministral-3-8b",
  "rnj-1-8b",

  // ===== Niche / Free-tier — OpenRouter =====
  "aurora-alpha",
  "dolphin-mistral-24b-venice-edition",
  "glm-4.5-air",
  "hermes-3-llama-3.1-405b",
  "lfm-2.5-1.2b-instruct",
  "lfm-2.5-1.2b-thinking",
  "nemotron-3-nano-30b-a3b",
  "nemotron-nano-12b-v2-vl",
  "qwen3-4b",
  "qwen3-vl-30b-a3b-thinking",
  "solar-pro-3",
  "step-3.5-flash",
  "trinity-large-preview",
  "trinity-mini",
]);
