release_date = "2024-04-23"
knowledge = "2023-10"
reasoning = false
tool_call = false
attachment = false

[cost]
input = 0.13
output = 0.52

[limit]
context = 4_096
output = 1_024

[modalities]
input = ["text"]
output = ["text"]

[opendum]
family = "Microsoft"
providers = []
