release_date = "2024-04-23"
knowledge = "2023-10"
reasoning = false
tool_call = false
attachment = false

[cost]
input = 0.15
output = 0.6

[limit]
context = 8_192
output = 2_048

[modalities]
input = ["text"]
output = ["text"]

[opendum]
family = "Microsoft"
providers = []
aliases = ["microsoft-phi-3-small-8k-instruct", "microsoft/phi-3-small-8k-instruct"]
ignored = true
