import os from "node:os";

export {
  CODEX_AUTHORIZE_ENDPOINT as AUTHORIZE_ENDPOINT,
  CODEX_BROWSER_REDIRECT_URI as BROWSER_REDIRECT_URI,
  CODEX_CLIENT_ID as CLIENT_ID,
  CODEX_DEVICE_CODE_ENDPOINT as DEVICE_CODE_ENDPOINT,
  CODEX_DEVICE_REDIRECT_URI as DEVICE_REDIRECT_URI,
  CODEX_DEVICE_TOKEN_ENDPOINT as DEVICE_TOKEN_ENDPOINT,
  CODEX_DEVICE_VERIFICATION_URL as DEVICE_VERIFICATION_URL,
  CODEX_ORIGINATOR as ORIGINATOR,
  CODEX_REFRESH_BUFFER_SECONDS as REFRESH_BUFFER_SECONDS,
  CODEX_SCOPE as SCOPE,
  CODEX_TOKEN_ENDPOINT as TOKEN_ENDPOINT,
} from "@opendum/providers/endpoints";

const OPENCODE_VERSION = "1.14.28";
export const CODEX_CHAT_USER_AGENT = `opencode/${OPENCODE_VERSION} (${os.platform()} ${os.release()}; ${os.arch()})`;
