release_date = "2025-08-19"
knowledge = "2024-07"
reasoning = true
tool_call = true
attachment = false

[cost]
input = 0.56
output = 1.68

[limit]
context = 128_000
output = 32_000

[modalities]
input = ["text"]
output = ["text"]

[opendum]
family = "DeepSeek"
providers = []
