import { Hono } from "hono";
import route0 from "./auth/[...all]";
import route1 from "./dashboard/accounts/codex-session.post";
import route2 from "./dashboard/accounts/create.post";
import route3 from "./dashboard/accounts/delete.post";
import route4 from "./dashboard/accounts/device-auth/initiate.post";
import route5 from "./dashboard/accounts/device-auth/poll.post";
import route6 from "./dashboard/accounts/errors/batch.post";
import route7 from "./dashboard/accounts/errors/index.get";
import route8 from "./dashboard/accounts/errors/resolve.post";
import route9 from "./dashboard/accounts/index.get";
import route10 from "./dashboard/accounts/model-enabled.post";
import route11 from "./dashboard/accounts/oauth/exchange.post";
import route12 from "./dashboard/accounts/oauth/url.post";
import route13 from "./dashboard/accounts/overview.get";
import route14 from "./dashboard/accounts/ping.get";
import route15 from "./dashboard/accounts/pinned.post";
import route16 from "./dashboard/accounts/provider-detail.get";
import route17 from "./dashboard/accounts/provider.get";
import route18 from "./dashboard/accounts/quota.post";
import route19 from "./dashboard/accounts/quotas.post";
import route20 from "./dashboard/accounts/stats.get";
import route21 from "./dashboard/accounts/update.post";
import route22 from "./dashboard/analytics/data.post";
import route23 from "./dashboard/analytics/overview.get";
import route24 from "./dashboard/analytics/series.post";
import route25 from "./dashboard/analytics/usage.get";
import route26 from "./dashboard/api-keys/account-access.post";
import route27 from "./dashboard/api-keys/create.post";
import route28 from "./dashboard/api-keys/delete.post";
import route29 from "./dashboard/api-keys/expiration.post";
import route30 from "./dashboard/api-keys/index.get";
import route31 from "./dashboard/api-keys/model-access.post";
import route32 from "./dashboard/api-keys/name.post";
import route33 from "./dashboard/api-keys/options.get";
import route34 from "./dashboard/api-keys/rate-limits.post";
import route35 from "./dashboard/api-keys/reveal.post";
import route36 from "./dashboard/api-keys/roaming.post";
import route37 from "./dashboard/api-keys/toggle.post";
import route38 from "./dashboard/maintener/audit/start.post";
import route39 from "./dashboard/maintener/audit/stop.post";
import route40 from "./dashboard/maintener/users/search.get";
import route41 from "./dashboard/me.get";
import route42 from "./dashboard/models/enabled.post";
import route43 from "./dashboard/models/families.get";
import route44 from "./dashboard/models/index.get";
import route45 from "./dashboard/models/search.get";
import route46 from "./dashboard/models/stats.get";
import route47 from "./dashboard/playground/auth.post";
import route48 from "./dashboard/playground/options.get";
import route49 from "./dashboard/points.get";
import route50 from "./dashboard/sharing/index.get";
import route51 from "./dashboard/sharing/index.post";

const app = new Hono();
app.route("/dashboard/auth/[...all]", route0);
app.route("/dashboard/accounts/codex-session", route1);
app.route("/dashboard/accounts/create", route2);
app.route("/dashboard/accounts/delete", route3);
app.route("/dashboard/accounts/device-auth/initiate", route4);
app.route("/dashboard/accounts/device-auth/poll", route5);
app.route("/dashboard/accounts/errors/batch", route6);
app.route("/dashboard/accounts/errors/index", route7);
app.route("/dashboard/accounts/errors/resolve", route8);
app.route("/dashboard/accounts/index", route9);
app.route("/dashboard/accounts/model-enabled", route10);
app.route("/dashboard/accounts/oauth/exchange", route11);
app.route("/dashboard/accounts/oauth/url", route12);
app.route("/dashboard/accounts/overview", route13);
app.route("/dashboard/accounts/ping", route14);
app.route("/dashboard/accounts/pinned", route15);
app.route("/dashboard/accounts/provider-detail", route16);
app.route("/dashboard/accounts/provider", route17);
app.route("/dashboard/accounts/quota", route18);
app.route("/dashboard/accounts/quotas", route19);
app.route("/dashboard/accounts/stats", route20);
app.route("/dashboard/accounts/update", route21);
app.route("/dashboard/analytics/data", route22);
app.route("/dashboard/analytics/overview", route23);
app.route("/dashboard/analytics/series", route24);
app.route("/dashboard/analytics/usage", route25);
app.route("/dashboard/api-keys/account-access", route26);
app.route("/dashboard/api-keys/create", route27);
app.route("/dashboard/api-keys/delete", route28);
app.route("/dashboard/api-keys/expiration", route29);
app.route("/dashboard/api-keys/index", route30);
app.route("/dashboard/api-keys/model-access", route31);
app.route("/dashboard/api-keys/name", route32);
app.route("/dashboard/api-keys/options", route33);
app.route("/dashboard/api-keys/rate-limits", route34);
app.route("/dashboard/api-keys/reveal", route35);
app.route("/dashboard/api-keys/roaming", route36);
app.route("/dashboard/api-keys/toggle", route37);
app.route("/dashboard/maintener/audit/start", route38);
app.route("/dashboard/maintener/audit/stop", route39);
app.route("/dashboard/maintener/users/search", route40);
app.route("/dashboard/me", route41);
app.route("/dashboard/models/enabled", route42);
app.route("/dashboard/models/families", route43);
app.route("/dashboard/models/index", route44);
app.route("/dashboard/models/search", route45);
app.route("/dashboard/models/stats", route46);
app.route("/dashboard/playground/auth", route47);
app.route("/dashboard/playground/options", route48);
app.route("/dashboard/points", route49);
app.route("/dashboard/sharing/index", route50);
app.route("/dashboard/sharing/index", route51);

export default app;
