
[limit]
context = 128_000
output = 4096

[modalities]
input = ["text"]
output = ["text"]

[opendum]
providers = ["nvidia_nim"]
aliases = ["mistralai-mistral-small-3.1-24b-instruct-2503", "mistralai/mistral-small-3.1-24b-instruct-2503"]
ignored = true
