release_date = "2024-12-01"
reasoning = false
tool_call = false
attachment = true

[limit]
context = 131_072
output = 131_072

[opendum]
providers = ["ollama_cloud"]
aliases = ["gemma-3-4b-it"]
ignored = true

[opendum.upstream]
ollama_cloud = "gemma3:4b"
