// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: api_key.sql

package db

import (
	"context"
	"time"
)

const deactivateAPIKey = `-- name: DeactivateAPIKey :exec
UPDATE proxy_api_key SET "isActive" = FALSE WHERE id = $1
`

func (q *Queries) DeactivateAPIKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deactivateAPIKey, id)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, "userId", "isActive", "expiresAt", "updatedAt", "modelAccessMode", "modelAccessList", "accountAccessMode", "accountAccessList", "roamingEnabled"
FROM proxy_api_key
WHERE "keyHash" = $1
LIMIT 1
`

type GetAPIKeyByHashRow struct {
	ID                string
	UserID            string
	IsActive          bool
	ExpiresAt         *time.Time
	UpdatedAt         time.Time
	ModelAccessMode   string
	ModelAccessList   []string
	AccountAccessMode string
	AccountAccessList []string
	RoamingEnabled    bool
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyhash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyhash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IsActive,
		&i.ExpiresAt,
		&i.UpdatedAt,
		&i.ModelAccessMode,
		&i.ModelAccessList,
		&i.AccountAccessMode,
		&i.AccountAccessList,
		&i.RoamingEnabled,
	)
	return i, err
}

const getAPIKeyFreshnessByID = `-- name: GetAPIKeyFreshnessByID :one
SELECT id, "isActive", "expiresAt", "updatedAt"
FROM proxy_api_key
WHERE id = $1
LIMIT 1
`

type GetAPIKeyFreshnessByIDRow struct {
	ID        string
	IsActive  bool
	ExpiresAt *time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetAPIKeyFreshnessByID(ctx context.Context, id string) (GetAPIKeyFreshnessByIDRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyFreshnessByID, id)
	var i GetAPIKeyFreshnessByIDRow
	err := row.Scan(
		&i.ID,
		&i.IsActive,
		&i.ExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeyRateLimits = `-- name: ListAPIKeyRateLimits :many
SELECT target, "targetType", "perMinute", "perHour", "perDay"
FROM proxy_api_key_rate_limit
WHERE "apiKeyId" = $1
`

type ListAPIKeyRateLimitsRow struct {
	Target     string
	TargetType string
	PerMinute  *int
	PerHour    *int
	PerDay     *int
}

func (q *Queries) ListAPIKeyRateLimits(ctx context.Context, apikeyid string) ([]ListAPIKeyRateLimitsRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeyRateLimits, apikeyid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeyRateLimitsRow{}
	for rows.Next() {
		var i ListAPIKeyRateLimitsRow
		if err := rows.Scan(
			&i.Target,
			&i.TargetType,
			&i.PerMinute,
			&i.PerHour,
			&i.PerDay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE proxy_api_key SET "lastUsedAt" = NOW() WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}
