// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: availability.sql

package db

import (
	"context"
	"time"
)

const listActiveAccountTiers = `-- name: ListActiveAccountTiers :many
SELECT id, provider, tier FROM provider_account
WHERE "userId" = $1
  AND "isActive"
  AND ("disabledUntil" IS NULL OR "disabledUntil" <= $2)
`

type ListActiveAccountTiersParams struct {
	UserID        string
	DisabledUntil *time.Time
}

type ListActiveAccountTiersRow struct {
	ID       string
	Provider string
	Tier     *string
}

func (q *Queries) ListActiveAccountTiers(ctx context.Context, arg ListActiveAccountTiersParams) ([]ListActiveAccountTiersRow, error) {
	rows, err := q.db.Query(ctx, listActiveAccountTiers, arg.UserID, arg.DisabledUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAccountTiersRow{}
	for rows.Next() {
		var i ListActiveAccountTiersRow
		if err := rows.Scan(&i.ID, &i.Provider, &i.Tier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisabledAccountIDs = `-- name: ListDisabledAccountIDs :many
SELECT "providerAccountId" FROM provider_account_disabled_model
WHERE "providerAccountId" = ANY($1::text[])
  AND model = ANY($2::text[])
`

type ListDisabledAccountIDsParams struct {
	AccountIds []string
	Models     []string
}

func (q *Queries) ListDisabledAccountIDs(ctx context.Context, arg ListDisabledAccountIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listDisabledAccountIDs, arg.AccountIds, arg.Models)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var providerAccountId string
		if err := rows.Scan(&providerAccountId); err != nil {
			return nil, err
		}
		items = append(items, providerAccountId)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisabledModelsByAccounts = `-- name: ListDisabledModelsByAccounts :many
SELECT "providerAccountId", model FROM provider_account_disabled_model
WHERE "providerAccountId" = ANY($1::text[])
`

type ListDisabledModelsByAccountsRow struct {
	ProviderAccountID string
	Model             string
}

func (q *Queries) ListDisabledModelsByAccounts(ctx context.Context, accountIds []string) ([]ListDisabledModelsByAccountsRow, error) {
	rows, err := q.db.Query(ctx, listDisabledModelsByAccounts, accountIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDisabledModelsByAccountsRow{}
	for rows.Next() {
		var i ListDisabledModelsByAccountsRow
		if err := rows.Scan(&i.ProviderAccountID, &i.Model); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisabledModelsByUser = `-- name: ListDisabledModelsByUser :many
SELECT model FROM disabled_model WHERE "userId" = $1
`

func (q *Queries) ListDisabledModelsByUser(ctx context.Context, userid string) ([]string, error) {
	rows, err := q.db.Query(ctx, listDisabledModelsByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var model string
		if err := rows.Scan(&model); err != nil {
			return nil, err
		}
		items = append(items, model)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedAccounts = `-- name: ListSharedAccounts :many
SELECT provider_account.id, provider_account.provider, provider_account.tier
FROM provider_account
JOIN user_sharing_setting ON user_sharing_setting."userId" = provider_account."userId"
WHERE provider_account."userId" <> $1
  AND user_sharing_setting.enabled
  AND provider_account."isActive"
  AND (provider_account."disabledUntil" IS NULL OR provider_account."disabledUntil" <= $2)
`

type ListSharedAccountsParams struct {
	UserID        string
	DisabledUntil *time.Time
}

type ListSharedAccountsRow struct {
	ID       string
	Provider string
	Tier     *string
}

func (q *Queries) ListSharedAccounts(ctx context.Context, arg ListSharedAccountsParams) ([]ListSharedAccountsRow, error) {
	rows, err := q.db.Query(ctx, listSharedAccounts, arg.UserID, arg.DisabledUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedAccountsRow{}
	for rows.Next() {
		var i ListSharedAccountsRow
		if err := rows.Scan(&i.ID, &i.Provider, &i.Tier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
