// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: model_health.sql

package db

import (
	"context"
	"time"
)

const bumpAccountRequestCount = `-- name: BumpAccountRequestCount :exec
UPDATE provider_account
SET "lastUsedAt" = $1, "requestCount" = "requestCount" + 1
WHERE id = $2
`

type BumpAccountRequestCountParams struct {
	LastUsedAt *time.Time
	ID         string
}

func (q *Queries) BumpAccountRequestCount(ctx context.Context, arg BumpAccountRequestCountParams) error {
	_, err := q.db.Exec(ctx, bumpAccountRequestCount, arg.LastUsedAt, arg.ID)
	return err
}

const getAccountHealthState = `-- name: GetAccountHealthState :one
SELECT id, status, "disabledUntil", "consecutiveErrors"
FROM provider_account
WHERE id = $1
LIMIT 1
`

type GetAccountHealthStateRow struct {
	ID                string
	Status            string
	DisabledUntil     *time.Time
	ConsecutiveErrors int
}

func (q *Queries) GetAccountHealthState(ctx context.Context, id string) (GetAccountHealthStateRow, error) {
	row := q.db.QueryRow(ctx, getAccountHealthState, id)
	var i GetAccountHealthStateRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.DisabledUntil,
		&i.ConsecutiveErrors,
	)
	return i, err
}

const getModelHealth = `-- name: GetModelHealth :one
SELECT id, "providerAccountId", model, "consecutiveErrors", status, "statusChangedAt", "lastErrorAt", "lastErrorCode", "lastSuccessAt", "unhealthyCountUpdatedAt", "createdAt", "updatedAt"
FROM provider_account_model_health
WHERE "providerAccountId" = $1 AND model = $2
LIMIT 1
`

type GetModelHealthParams struct {
	ProviderAccountID string
	Model             string
}

func (q *Queries) GetModelHealth(ctx context.Context, arg GetModelHealthParams) (ProviderAccountModelHealth, error) {
	row := q.db.QueryRow(ctx, getModelHealth, arg.ProviderAccountID, arg.Model)
	var i ProviderAccountModelHealth
	err := row.Scan(
		&i.ID,
		&i.ProviderAccountID,
		&i.Model,
		&i.ConsecutiveErrors,
		&i.Status,
		&i.StatusChangedAt,
		&i.LastErrorAt,
		&i.LastErrorCode,
		&i.LastSuccessAt,
		&i.UnhealthyCountUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertModelHealth = `-- name: InsertModelHealth :exec
INSERT INTO provider_account_model_health (id, "providerAccountId", model, "consecutiveErrors", status, "lastErrorAt", "lastErrorCode", "unhealthyCountUpdatedAt", "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertModelHealthParams struct {
	ID                      string
	ProviderAccountID       string
	Model                   string
	ConsecutiveErrors       int
	Status                  string
	LastErrorAt             *time.Time
	LastErrorCode           *int
	UnhealthyCountUpdatedAt *time.Time
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

func (q *Queries) InsertModelHealth(ctx context.Context, arg InsertModelHealthParams) error {
	_, err := q.db.Exec(ctx, insertModelHealth,
		arg.ID,
		arg.ProviderAccountID,
		arg.Model,
		arg.ConsecutiveErrors,
		arg.Status,
		arg.LastErrorAt,
		arg.LastErrorCode,
		arg.UnhealthyCountUpdatedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listModelHealthByAccount = `-- name: ListModelHealthByAccount :many
SELECT id, "providerAccountId", model, "consecutiveErrors", status, "statusChangedAt", "lastErrorAt", "lastErrorCode", "lastSuccessAt", "unhealthyCountUpdatedAt", "createdAt", "updatedAt"
FROM provider_account_model_health
WHERE "providerAccountId" = $1
`

func (q *Queries) ListModelHealthByAccount(ctx context.Context, provideraccountid string) ([]ProviderAccountModelHealth, error) {
	rows, err := q.db.Query(ctx, listModelHealthByAccount, provideraccountid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderAccountModelHealth{}
	for rows.Next() {
		var i ProviderAccountModelHealth
		if err := rows.Scan(
			&i.ID,
			&i.ProviderAccountID,
			&i.Model,
			&i.ConsecutiveErrors,
			&i.Status,
			&i.StatusChangedAt,
			&i.LastErrorAt,
			&i.LastErrorCode,
			&i.LastSuccessAt,
			&i.UnhealthyCountUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelHealthByAccounts = `-- name: ListModelHealthByAccounts :many
SELECT id, "providerAccountId", model, "consecutiveErrors", status, "statusChangedAt", "lastErrorAt", "lastErrorCode", "lastSuccessAt", "unhealthyCountUpdatedAt", "createdAt", "updatedAt"
FROM provider_account_model_health
WHERE "providerAccountId" = ANY($1::text[])
  AND model = ANY($2::text[])
`

type ListModelHealthByAccountsParams struct {
	AccountIds []string
	Models     []string
}

func (q *Queries) ListModelHealthByAccounts(ctx context.Context, arg ListModelHealthByAccountsParams) ([]ProviderAccountModelHealth, error) {
	rows, err := q.db.Query(ctx, listModelHealthByAccounts, arg.AccountIds, arg.Models)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderAccountModelHealth{}
	for rows.Next() {
		var i ProviderAccountModelHealth
		if err := rows.Scan(
			&i.ID,
			&i.ProviderAccountID,
			&i.Model,
			&i.ConsecutiveErrors,
			&i.Status,
			&i.StatusChangedAt,
			&i.LastErrorAt,
			&i.LastErrorCode,
			&i.LastSuccessAt,
			&i.UnhealthyCountUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAccountRecoveredByRotation = `-- name: MarkAccountRecoveredByRotation :exec
UPDATE provider_account
SET "lastRecoveredByRotationAt" = $1
WHERE id = $2 AND "lastErrorAt" <= $3
`

type MarkAccountRecoveredByRotationParams struct {
	LastRecoveredByRotationAt *time.Time
	ID                        string
	LastErrorAt               *time.Time
}

func (q *Queries) MarkAccountRecoveredByRotation(ctx context.Context, arg MarkAccountRecoveredByRotationParams) error {
	_, err := q.db.Exec(ctx, markAccountRecoveredByRotation, arg.LastRecoveredByRotationAt, arg.ID, arg.LastErrorAt)
	return err
}

const markAccountSuccess = `-- name: MarkAccountSuccess :exec
UPDATE provider_account
SET "successCount" = "successCount" + 1, "lastSuccessAt" = $1
WHERE id = $2
`

type MarkAccountSuccessParams struct {
	LastSuccessAt *time.Time
	ID            string
}

func (q *Queries) MarkAccountSuccess(ctx context.Context, arg MarkAccountSuccessParams) error {
	_, err := q.db.Exec(ctx, markAccountSuccess, arg.LastSuccessAt, arg.ID)
	return err
}

const markUsageLimitedHealth = `-- name: MarkUsageLimitedHealth :exec
UPDATE provider_account_model_health
SET status = $1, "statusChangedAt" = $2, "consecutiveErrors" = $3, "lastErrorAt" = $2, "unhealthyCountUpdatedAt" = $2
WHERE "providerAccountId" = $4 AND model = $5
`

type MarkUsageLimitedHealthParams struct {
	Status            string
	StatusChangedAt   *time.Time
	ConsecutiveErrors int
	ProviderAccountID string
	Model             string
}

func (q *Queries) MarkUsageLimitedHealth(ctx context.Context, arg MarkUsageLimitedHealthParams) error {
	_, err := q.db.Exec(ctx, markUsageLimitedHealth,
		arg.Status,
		arg.StatusChangedAt,
		arg.ConsecutiveErrors,
		arg.ProviderAccountID,
		arg.Model,
	)
	return err
}

const recordRequestError = `-- name: RecordRequestError :exec
UPDATE provider_account
SET "errorCount" = "errorCount" + 1, "lastErrorAt" = $1, "lastErrorCode" = $2
WHERE id = $3
`

type RecordRequestErrorParams struct {
	LastErrorAt   *time.Time
	LastErrorCode *int
	ID            string
}

func (q *Queries) RecordRequestError(ctx context.Context, arg RecordRequestErrorParams) error {
	_, err := q.db.Exec(ctx, recordRequestError, arg.LastErrorAt, arg.LastErrorCode, arg.ID)
	return err
}

const setAccountActive = `-- name: SetAccountActive :exec
UPDATE provider_account
SET status = $1, "statusChangedAt" = $2, "consecutiveErrors" = $3, "disabledUntil" = NULL
WHERE id = $4
`

type SetAccountActiveParams struct {
	Status            string
	StatusChangedAt   *time.Time
	ConsecutiveErrors int
	ID                string
}

func (q *Queries) SetAccountActive(ctx context.Context, arg SetAccountActiveParams) error {
	_, err := q.db.Exec(ctx, setAccountActive,
		arg.Status,
		arg.StatusChangedAt,
		arg.ConsecutiveErrors,
		arg.ID,
	)
	return err
}

const setAccountCooldown = `-- name: SetAccountCooldown :exec
UPDATE provider_account
SET status = $1, "statusChangedAt" = $2, "consecutiveErrors" = $3, "disabledUntil" = $4
WHERE id = $5
`

type SetAccountCooldownParams struct {
	Status            string
	StatusChangedAt   *time.Time
	ConsecutiveErrors int
	DisabledUntil     *time.Time
	ID                string
}

func (q *Queries) SetAccountCooldown(ctx context.Context, arg SetAccountCooldownParams) error {
	_, err := q.db.Exec(ctx, setAccountCooldown,
		arg.Status,
		arg.StatusChangedAt,
		arg.ConsecutiveErrors,
		arg.DisabledUntil,
		arg.ID,
	)
	return err
}

const setAccountHealthFailed = `-- name: SetAccountHealthFailed :exec
UPDATE provider_account
SET "consecutiveErrors" = $1, status = $2, "statusChangedAt" = $3
WHERE id = $4
`

type SetAccountHealthFailedParams struct {
	ConsecutiveErrors int
	Status            string
	StatusChangedAt   *time.Time
	ID                string
}

func (q *Queries) SetAccountHealthFailed(ctx context.Context, arg SetAccountHealthFailedParams) error {
	_, err := q.db.Exec(ctx, setAccountHealthFailed,
		arg.ConsecutiveErrors,
		arg.Status,
		arg.StatusChangedAt,
		arg.ID,
	)
	return err
}

const setAccountUsageLimited = `-- name: SetAccountUsageLimited :exec
UPDATE provider_account
SET "disabledUntil" = $1, status = $2, "statusChangedAt" = $3
WHERE id = $4
`

type SetAccountUsageLimitedParams struct {
	DisabledUntil   *time.Time
	Status          string
	StatusChangedAt *time.Time
	ID              string
}

func (q *Queries) SetAccountUsageLimited(ctx context.Context, arg SetAccountUsageLimitedParams) error {
	_, err := q.db.Exec(ctx, setAccountUsageLimited,
		arg.DisabledUntil,
		arg.Status,
		arg.StatusChangedAt,
		arg.ID,
	)
	return err
}

const updateModelHealthCounters = `-- name: UpdateModelHealthCounters :exec
UPDATE provider_account_model_health
SET "consecutiveErrors" = $1, "unhealthyCountUpdatedAt" = $2
WHERE id = $3
`

type UpdateModelHealthCountersParams struct {
	ConsecutiveErrors       int
	UnhealthyCountUpdatedAt *time.Time
	ID                      string
}

func (q *Queries) UpdateModelHealthCounters(ctx context.Context, arg UpdateModelHealthCountersParams) error {
	_, err := q.db.Exec(ctx, updateModelHealthCounters, arg.ConsecutiveErrors, arg.UnhealthyCountUpdatedAt, arg.ID)
	return err
}

const updateModelHealthFailure = `-- name: UpdateModelHealthFailure :exec
UPDATE provider_account_model_health
SET "consecutiveErrors" = $1, "lastErrorAt" = $2, "lastErrorCode" = $3, "unhealthyCountUpdatedAt" = $4
WHERE id = $5
`

type UpdateModelHealthFailureParams struct {
	ConsecutiveErrors       int
	LastErrorAt             *time.Time
	LastErrorCode           *int
	UnhealthyCountUpdatedAt *time.Time
	ID                      string
}

func (q *Queries) UpdateModelHealthFailure(ctx context.Context, arg UpdateModelHealthFailureParams) error {
	_, err := q.db.Exec(ctx, updateModelHealthFailure,
		arg.ConsecutiveErrors,
		arg.LastErrorAt,
		arg.LastErrorCode,
		arg.UnhealthyCountUpdatedAt,
		arg.ID,
	)
	return err
}

const updateModelHealthFailureWithStatus = `-- name: UpdateModelHealthFailureWithStatus :exec
UPDATE provider_account_model_health
SET "consecutiveErrors" = $1, "lastErrorAt" = $2, "lastErrorCode" = $3, "unhealthyCountUpdatedAt" = $4, status = $5, "statusChangedAt" = $6
WHERE id = $7
`

type UpdateModelHealthFailureWithStatusParams struct {
	ConsecutiveErrors       int
	LastErrorAt             *time.Time
	LastErrorCode           *int
	UnhealthyCountUpdatedAt *time.Time
	Status                  string
	StatusChangedAt         *time.Time
	ID                      string
}

func (q *Queries) UpdateModelHealthFailureWithStatus(ctx context.Context, arg UpdateModelHealthFailureWithStatusParams) error {
	_, err := q.db.Exec(ctx, updateModelHealthFailureWithStatus,
		arg.ConsecutiveErrors,
		arg.LastErrorAt,
		arg.LastErrorCode,
		arg.UnhealthyCountUpdatedAt,
		arg.Status,
		arg.StatusChangedAt,
		arg.ID,
	)
	return err
}

const updateModelHealthStatus = `-- name: UpdateModelHealthStatus :exec
UPDATE provider_account_model_health
SET "consecutiveErrors" = $1, "unhealthyCountUpdatedAt" = $2, status = $3, "statusChangedAt" = $4
WHERE id = $5
`

type UpdateModelHealthStatusParams struct {
	ConsecutiveErrors       int
	UnhealthyCountUpdatedAt *time.Time
	Status                  string
	StatusChangedAt         *time.Time
	ID                      string
}

func (q *Queries) UpdateModelHealthStatus(ctx context.Context, arg UpdateModelHealthStatusParams) error {
	_, err := q.db.Exec(ctx, updateModelHealthStatus,
		arg.ConsecutiveErrors,
		arg.UnhealthyCountUpdatedAt,
		arg.Status,
		arg.StatusChangedAt,
		arg.ID,
	)
	return err
}

const updateModelHealthSuccess = `-- name: UpdateModelHealthSuccess :exec
UPDATE provider_account_model_health
SET "consecutiveErrors" = $1, "lastSuccessAt" = $2, "unhealthyCountUpdatedAt" = $3
WHERE id = $4
`

type UpdateModelHealthSuccessParams struct {
	ConsecutiveErrors       int
	LastSuccessAt           *time.Time
	UnhealthyCountUpdatedAt *time.Time
	ID                      string
}

func (q *Queries) UpdateModelHealthSuccess(ctx context.Context, arg UpdateModelHealthSuccessParams) error {
	_, err := q.db.Exec(ctx, updateModelHealthSuccess,
		arg.ConsecutiveErrors,
		arg.LastSuccessAt,
		arg.UnhealthyCountUpdatedAt,
		arg.ID,
	)
	return err
}

const updateModelHealthSuccessWithStatus = `-- name: UpdateModelHealthSuccessWithStatus :exec
UPDATE provider_account_model_health
SET "consecutiveErrors" = $1, "lastSuccessAt" = $2, "unhealthyCountUpdatedAt" = $3, status = $4, "statusChangedAt" = $5
WHERE id = $6
`

type UpdateModelHealthSuccessWithStatusParams struct {
	ConsecutiveErrors       int
	LastSuccessAt           *time.Time
	UnhealthyCountUpdatedAt *time.Time
	Status                  string
	StatusChangedAt         *time.Time
	ID                      string
}

func (q *Queries) UpdateModelHealthSuccessWithStatus(ctx context.Context, arg UpdateModelHealthSuccessWithStatusParams) error {
	_, err := q.db.Exec(ctx, updateModelHealthSuccessWithStatus,
		arg.ConsecutiveErrors,
		arg.LastSuccessAt,
		arg.UnhealthyCountUpdatedAt,
		arg.Status,
		arg.StatusChangedAt,
		arg.ID,
	)
	return err
}
