// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Account struct {
	ID                    string
	UserID                string
	AccountID             string
	ProviderID            string
	AccessToken           *string
	RefreshToken          *string
	AccessTokenExpiresAt  *time.Time
	RefreshTokenExpiresAt *time.Time
	Scope                 *string
	IDToken               *string
	Password              *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type DisabledModel struct {
	ID        string
	UserID    string
	Model     string
	CreatedAt time.Time
}

type PinnedProvider struct {
	ID          string
	UserID      string
	ProviderKey string
	CreatedAt   time.Time
}

type PointTransaction struct {
	ID             string
	UserID         string
	Amount         int
	Type           string
	BalanceAfter   int
	IdempotencyKey *string
	UsageLogId     *string
	CreatedAt      time.Time
}

type ProviderAccount struct {
	ID                        string
	UserID                    string
	Provider                  string
	Name                      string
	AccessToken               string
	RefreshToken              string
	ExpiresAt                 time.Time
	APIKey                    *string
	ProjectID                 *string
	Tier                      *string
	AccountID                 *string
	Email                     *string
	IsActive                  bool
	DisabledUntil             *time.Time
	LastUsedAt                *time.Time
	RequestCount              int
	ErrorCount                int
	ConsecutiveErrors         int
	LastErrorAt               *time.Time
	LastErrorCode             *int
	LastRecoveredByRotationAt *time.Time
	Status                    string
	StatusChangedAt           *time.Time
	SuccessCount              int
	LastSuccessAt             *time.Time
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}

type ProviderAccountDisabledModel struct {
	ID                string
	ProviderAccountID string
	Model             string
	CreatedAt         time.Time
}

type ProviderAccountModelHealth struct {
	ID                      string
	ProviderAccountID       string
	Model                   string
	ConsecutiveErrors       int
	Status                  string
	StatusChangedAt         *time.Time
	LastErrorAt             *time.Time
	LastErrorCode           *int
	LastSuccessAt           *time.Time
	UnhealthyCountUpdatedAt *time.Time
	CreatedAt               time.Time
	UpdatedAt               time.Time
	QuotaLockedUntil        *time.Time
	QuotaLockReason         *string
}

type ProxyAPIKey struct {
	ID                string
	UserID            string
	KeyHash           string
	KeyPreview        string
	EncryptedKey      *string
	Name              *string
	ModelAccessMode   string
	ModelAccessList   []string
	AccountAccessMode string
	AccountAccessList []string
	RoamingEnabled    bool
	IsActive          bool
	ExpiresAt         *time.Time
	LastUsedAt        *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ProxyAPIKeyRateLimit struct {
	ID         string
	APIKeyID   string
	Target     string
	TargetType string
	PerMinute  *int
	PerHour    *int
	PerDay     *int
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Session struct {
	ID        string
	UserID    string
	Token     string
	ExpiresAt time.Time
	IPAddress *string
	UserAgent *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UsageLog struct {
	ID                string
	UserID            string
	ProviderAccountID *string
	ProxyAPIKeyID     *string
	Model             string
	InputTokens       int
	OutputTokens      int
	StatusCode        *int
	Duration          *int
	CreatedAt         time.Time
}

type User struct {
	ID            string
	Name          string
	Email         string
	EmailVerified bool
	Image         *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type UserPointBalance struct {
	UserID    string
	Balance   int
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserSharingSetting struct {
	UserID    string
	Enabled   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Verification struct {
	ID         string
	Identifier string
	Value      string
	ExpiresAt  time.Time
	CreatedAt  *time.Time
	UpdatedAt  *time.Time
}
