// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: provider_account.sql

package db

import (
	"context"
	"time"
)

const disableFailedAccount = `-- name: DisableFailedAccount :execrows
UPDATE provider_account
SET "isActive" = FALSE, status = $1, "statusChangedAt" = $2, "updatedAt" = $2
WHERE id = $3 AND "isActive"
`

type DisableFailedAccountParams struct {
	Status          string
	StatusChangedAt *time.Time
	ID              string
}

func (q *Queries) DisableFailedAccount(ctx context.Context, arg DisableFailedAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableFailedAccount, arg.Status, arg.StatusChangedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountCredentialsByID = `-- name: GetAccountCredentialsByID :one
SELECT id, "userId", provider, "accessToken", "refreshToken", "expiresAt", "accountId", "projectId", tier, email, "isActive"
FROM provider_account
WHERE id = $1
LIMIT 1
`

type GetAccountCredentialsByIDRow struct {
	ID           string
	UserID       string
	Provider     string
	AccessToken  string
	RefreshToken string
	ExpiresAt    time.Time
	AccountID    *string
	ProjectID    *string
	Tier         *string
	Email        *string
	IsActive     bool
}

func (q *Queries) GetAccountCredentialsByID(ctx context.Context, id string) (GetAccountCredentialsByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountCredentialsByID, id)
	var i GetAccountCredentialsByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.AccountID,
		&i.ProjectID,
		&i.Tier,
		&i.Email,
		&i.IsActive,
	)
	return i, err
}

const getAccountOwnerUserID = `-- name: GetAccountOwnerUserID :one
SELECT "userId" FROM provider_account WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccountOwnerUserID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getAccountOwnerUserID, id)
	var userId string
	err := row.Scan(&userId)
	return userId, err
}

const getForcedAccount = `-- name: GetForcedAccount :one
SELECT id, "userId", provider, tier, status, "lastUsedAt", "createdAt", "accountId", "isActive", "disabledUntil"
FROM provider_account
WHERE id = $1 AND "userId" = $2
LIMIT 1
`

type GetForcedAccountParams struct {
	ID     string
	UserID string
}

type GetForcedAccountRow struct {
	ID            string
	UserID        string
	Provider      string
	Tier          *string
	Status        string
	LastUsedAt    *time.Time
	CreatedAt     time.Time
	AccountID     *string
	IsActive      bool
	DisabledUntil *time.Time
}

func (q *Queries) GetForcedAccount(ctx context.Context, arg GetForcedAccountParams) (GetForcedAccountRow, error) {
	row := q.db.QueryRow(ctx, getForcedAccount, arg.ID, arg.UserID)
	var i GetForcedAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Tier,
		&i.Status,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.AccountID,
		&i.IsActive,
		&i.DisabledUntil,
	)
	return i, err
}

const getQuotaAccount = `-- name: GetQuotaAccount :one
SELECT id, "userId", provider, name, "accessToken", "refreshToken", "expiresAt", "apiKey", "projectId", tier, "accountId", email, "isActive", "lastUsedAt"
FROM provider_account
WHERE id = $1 AND "userId" = $2 AND provider = $3
LIMIT 1
`

type GetQuotaAccountParams struct {
	ID       string
	UserID   string
	Provider string
}

type GetQuotaAccountRow struct {
	ID           string
	UserID       string
	Provider     string
	Name         string
	AccessToken  string
	RefreshToken string
	ExpiresAt    time.Time
	APIKey       *string
	ProjectID    *string
	Tier         *string
	AccountID    *string
	Email        *string
	IsActive     bool
	LastUsedAt   *time.Time
}

func (q *Queries) GetQuotaAccount(ctx context.Context, arg GetQuotaAccountParams) (GetQuotaAccountRow, error) {
	row := q.db.QueryRow(ctx, getQuotaAccount, arg.ID, arg.UserID, arg.Provider)
	var i GetQuotaAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Name,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.APIKey,
		&i.ProjectID,
		&i.Tier,
		&i.AccountID,
		&i.Email,
		&i.IsActive,
		&i.LastUsedAt,
	)
	return i, err
}

const listEligibleAccounts = `-- name: ListEligibleAccounts :many
SELECT id, "userId", provider, tier, status, "lastUsedAt", "createdAt", "accountId", "disabledUntil"
FROM provider_account
WHERE "userId" = $1
  AND provider = ANY($2::text[])
  AND "isActive"
  AND ("disabledUntil" IS NULL OR "disabledUntil" <= $3)
  AND (CARDINALITY($4::text[]) = 0 OR NOT (id = ANY($4::text[])))
  AND (CARDINALITY($5::text[]) = 0 OR NOT (provider = ANY($5::text[])))
  AND CASE WHEN $6::boolean THEN id = ANY($7::text[]) WHEN $8::boolean THEN NOT (id = ANY($7::text[])) ELSE TRUE END
ORDER BY status ASC, "lastUsedAt" ASC NULLS FIRST, "createdAt" ASC
`

type ListEligibleAccountsParams struct {
	UserID           string
	Providers        []string
	Now              *time.Time
	ExcludeIds       []string
	ExcludeProviders []string
	UseWhitelist     bool
	AccountIds       []string
	UseBlacklist     bool
}

type ListEligibleAccountsRow struct {
	ID            string
	UserID        string
	Provider      string
	Tier          *string
	Status        string
	LastUsedAt    *time.Time
	CreatedAt     time.Time
	AccountID     *string
	DisabledUntil *time.Time
}

func (q *Queries) ListEligibleAccounts(ctx context.Context, arg ListEligibleAccountsParams) ([]ListEligibleAccountsRow, error) {
	rows, err := q.db.Query(ctx, listEligibleAccounts,
		arg.UserID,
		arg.Providers,
		arg.Now,
		arg.ExcludeIds,
		arg.ExcludeProviders,
		arg.UseWhitelist,
		arg.AccountIds,
		arg.UseBlacklist,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEligibleAccountsRow{}
	for rows.Next() {
		var i ListEligibleAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Tier,
			&i.Status,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.AccountID,
			&i.DisabledUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringRefreshableAccounts = `-- name: ListExpiringRefreshableAccounts :many
SELECT id, "userId", provider, "accessToken", "refreshToken", "expiresAt", "accountId", "projectId", tier, email, "isActive"
FROM provider_account
WHERE "isActive"
  AND ("disabledUntil" IS NULL OR "disabledUntil" <= $1)
  AND provider = $2
  AND "refreshToken" <> ''
  AND "expiresAt" <= $3
ORDER BY "expiresAt" ASC
LIMIT $4
`

type ListExpiringRefreshableAccountsParams struct {
	Now           *time.Time
	Provider      string
	ExpiresBefore time.Time
	BatchLimit    int32
}

type ListExpiringRefreshableAccountsRow struct {
	ID           string
	UserID       string
	Provider     string
	AccessToken  string
	RefreshToken string
	ExpiresAt    time.Time
	AccountID    *string
	ProjectID    *string
	Tier         *string
	Email        *string
	IsActive     bool
}

func (q *Queries) ListExpiringRefreshableAccounts(ctx context.Context, arg ListExpiringRefreshableAccountsParams) ([]ListExpiringRefreshableAccountsRow, error) {
	rows, err := q.db.Query(ctx, listExpiringRefreshableAccounts,
		arg.Now,
		arg.Provider,
		arg.ExpiresBefore,
		arg.BatchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringRefreshableAccountsRow{}
	for rows.Next() {
		var i ListExpiringRefreshableAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.AccessToken,
			&i.RefreshToken,
			&i.ExpiresAt,
			&i.AccountID,
			&i.ProjectID,
			&i.Tier,
			&i.Email,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedEligibleAccounts = `-- name: ListSharedEligibleAccounts :many
SELECT provider_account.id, provider_account."userId", provider_account.provider, provider_account.tier, provider_account.status, provider_account."lastUsedAt", provider_account."createdAt", provider_account."accountId", provider_account."disabledUntil"
FROM provider_account
JOIN user_sharing_setting ON user_sharing_setting."userId" = provider_account."userId"
WHERE provider_account."userId" <> $1
  AND user_sharing_setting.enabled
  AND provider_account.provider = ANY($2::text[])
  AND provider_account."isActive"
  AND (provider_account."disabledUntil" IS NULL OR provider_account."disabledUntil" <= $3)
  AND (CARDINALITY($4::text[]) = 0 OR NOT (provider_account.id = ANY($4::text[])))
  AND (CARDINALITY($5::text[]) = 0 OR NOT (provider_account.provider = ANY($5::text[])))
ORDER BY provider_account.status ASC, provider_account."lastUsedAt" ASC NULLS FIRST, provider_account."createdAt" ASC
`

type ListSharedEligibleAccountsParams struct {
	UserID           string
	Providers        []string
	Now              *time.Time
	ExcludeIds       []string
	ExcludeProviders []string
}

type ListSharedEligibleAccountsRow struct {
	ID            string
	UserID        string
	Provider      string
	Tier          *string
	Status        string
	LastUsedAt    *time.Time
	CreatedAt     time.Time
	AccountID     *string
	DisabledUntil *time.Time
}

func (q *Queries) ListSharedEligibleAccounts(ctx context.Context, arg ListSharedEligibleAccountsParams) ([]ListSharedEligibleAccountsRow, error) {
	rows, err := q.db.Query(ctx, listSharedEligibleAccounts,
		arg.UserID,
		arg.Providers,
		arg.Now,
		arg.ExcludeIds,
		arg.ExcludeProviders,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedEligibleAccountsRow{}
	for rows.Next() {
		var i ListSharedEligibleAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Tier,
			&i.Status,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.AccountID,
			&i.DisabledUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAccountError = `-- name: RecordAccountError :exec
UPDATE provider_account
SET "errorCount" = "errorCount" + 1, "lastErrorAt" = $1, "lastErrorCode" = $2, "updatedAt" = $1
WHERE id = $3
`

type RecordAccountErrorParams struct {
	LastErrorAt   *time.Time
	LastErrorCode *int
	ID            string
}

func (q *Queries) RecordAccountError(ctx context.Context, arg RecordAccountErrorParams) error {
	_, err := q.db.Exec(ctx, recordAccountError, arg.LastErrorAt, arg.LastErrorCode, arg.ID)
	return err
}

const updateAntigravityAccountInfo = `-- name: UpdateAntigravityAccountInfo :exec
UPDATE provider_account SET "projectId" = $1, tier = $2, email = $3 WHERE id = $4
`

type UpdateAntigravityAccountInfoParams struct {
	ProjectID *string
	Tier      *string
	Email     *string
	ID        string
}

func (q *Queries) UpdateAntigravityAccountInfo(ctx context.Context, arg UpdateAntigravityAccountInfoParams) error {
	_, err := q.db.Exec(ctx, updateAntigravityAccountInfo,
		arg.ProjectID,
		arg.Tier,
		arg.Email,
		arg.ID,
	)
	return err
}

const updateCodexAccountID = `-- name: UpdateCodexAccountID :exec
UPDATE provider_account SET "accountId" = $1 WHERE id = $2
`

type UpdateCodexAccountIDParams struct {
	AccountID *string
	ID        string
}

func (q *Queries) UpdateCodexAccountID(ctx context.Context, arg UpdateCodexAccountIDParams) error {
	_, err := q.db.Exec(ctx, updateCodexAccountID, arg.AccountID, arg.ID)
	return err
}

const updateRefreshedCredentials = `-- name: UpdateRefreshedCredentials :exec
UPDATE provider_account
SET "accessToken" = $1, "refreshToken" = $2, "expiresAt" = $3, "projectId" = $4, tier = $5, email = $6, "accountId" = $7, "updatedAt" = $8
WHERE id = $9
`

type UpdateRefreshedCredentialsParams struct {
	AccessToken  string
	RefreshToken string
	ExpiresAt    time.Time
	ProjectID    *string
	Tier         *string
	Email        *string
	AccountID    *string
	UpdatedAt    time.Time
	ID           string
}

func (q *Queries) UpdateRefreshedCredentials(ctx context.Context, arg UpdateRefreshedCredentialsParams) error {
	_, err := q.db.Exec(ctx, updateRefreshedCredentials,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.ProjectID,
		arg.Tier,
		arg.Email,
		arg.AccountID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
