// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: usage_points.sql

package db

import (
	"context"
	"time"
)

const creditPointBalance = `-- name: CreditPointBalance :one
UPDATE user_point_balance SET balance = balance + $1, "updatedAt" = $2 WHERE "userId" = $3 RETURNING balance
`

type CreditPointBalanceParams struct {
	Balance   int
	UpdatedAt time.Time
	UserID    string
}

func (q *Queries) CreditPointBalance(ctx context.Context, arg CreditPointBalanceParams) (int, error) {
	row := q.db.QueryRow(ctx, creditPointBalance, arg.Balance, arg.UpdatedAt, arg.UserID)
	var balance int
	err := row.Scan(&balance)
	return balance, err
}

const debitPointBalance = `-- name: DebitPointBalance :one
UPDATE user_point_balance SET balance = balance - $1, "updatedAt" = $2 WHERE "userId" = $3 AND balance >= $1 RETURNING balance
`

type DebitPointBalanceParams struct {
	Balance   int
	UpdatedAt time.Time
	UserID    string
}

func (q *Queries) DebitPointBalance(ctx context.Context, arg DebitPointBalanceParams) (int, error) {
	row := q.db.QueryRow(ctx, debitPointBalance, arg.Balance, arg.UpdatedAt, arg.UserID)
	var balance int
	err := row.Scan(&balance)
	return balance, err
}

const insertPointBalanceOnConflictDoNothing = `-- name: InsertPointBalanceOnConflictDoNothing :execrows
INSERT INTO user_point_balance ("userId", balance, "createdAt", "updatedAt")
VALUES ($1, $2, $3, $4) ON CONFLICT ("userId") DO NOTHING
`

type InsertPointBalanceOnConflictDoNothingParams struct {
	UserID    string
	Balance   int
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertPointBalanceOnConflictDoNothing(ctx context.Context, arg InsertPointBalanceOnConflictDoNothingParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPointBalanceOnConflictDoNothing,
		arg.UserID,
		arg.Balance,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPointTransaction = `-- name: InsertPointTransaction :exec
INSERT INTO point_transaction (id, "userId", amount, type, "balanceAfter", "idempotencyKey", "usageLogId", "createdAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertPointTransactionParams struct {
	ID             string
	UserID         string
	Amount         int
	Type           string
	BalanceAfter   int
	IdempotencyKey *string
	UsageLogId     *string
	CreatedAt      time.Time
}

func (q *Queries) InsertPointTransaction(ctx context.Context, arg InsertPointTransactionParams) error {
	_, err := q.db.Exec(ctx, insertPointTransaction,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.Type,
		arg.BalanceAfter,
		arg.IdempotencyKey,
		arg.UsageLogId,
		arg.CreatedAt,
	)
	return err
}

const insertPointTransactionOnConflictDoNothing = `-- name: InsertPointTransactionOnConflictDoNothing :execrows
INSERT INTO point_transaction (id, "userId", amount, type, "balanceAfter", "idempotencyKey", "usageLogId", "createdAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) ON CONFLICT ("idempotencyKey") DO NOTHING
`

type InsertPointTransactionOnConflictDoNothingParams struct {
	ID             string
	UserID         string
	Amount         int
	Type           string
	BalanceAfter   int
	IdempotencyKey *string
	UsageLogId     *string
	CreatedAt      time.Time
}

func (q *Queries) InsertPointTransactionOnConflictDoNothing(ctx context.Context, arg InsertPointTransactionOnConflictDoNothingParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPointTransactionOnConflictDoNothing,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.Type,
		arg.BalanceAfter,
		arg.IdempotencyKey,
		arg.UsageLogId,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertUsageLog = `-- name: InsertUsageLog :exec
INSERT INTO usage_log (id, "userId", "providerAccountId", "proxyApiKeyId", model, "inputTokens", "outputTokens", "statusCode", duration, "createdAt")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertUsageLogParams struct {
	ID                string
	UserID            string
	ProviderAccountID *string
	ProxyAPIKeyID     *string
	Model             string
	InputTokens       int
	OutputTokens      int
	StatusCode        *int
	Duration          *int
	CreatedAt         time.Time
}

func (q *Queries) InsertUsageLog(ctx context.Context, arg InsertUsageLogParams) error {
	_, err := q.db.Exec(ctx, insertUsageLog,
		arg.ID,
		arg.UserID,
		arg.ProviderAccountID,
		arg.ProxyAPIKeyID,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.StatusCode,
		arg.Duration,
		arg.CreatedAt,
	)
	return err
}

const updatePointTransactionBalance = `-- name: UpdatePointTransactionBalance :exec
UPDATE point_transaction SET "balanceAfter" = $1 WHERE id = $2
`

type UpdatePointTransactionBalanceParams struct {
	BalanceAfter int
	ID           string
}

func (q *Queries) UpdatePointTransactionBalance(ctx context.Context, arg UpdatePointTransactionBalanceParams) error {
	_, err := q.db.Exec(ctx, updatePointTransactionBalance, arg.BalanceAfter, arg.ID)
	return err
}
