release_date = "2026-02-09"
reasoning = false
tool_call = true
attachment = true

[limit]
context = 128_000
output = 32_000

[modalities]
input = ["text","image","video"]
output = ["text"]

[opendum]
family = "Qwen"
providers = []
