<script setup lang="ts">
import type { Component } from "vue";
import {
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BarChart3,
  BookOpen,
  Bot,
  Brain,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleDashed,
  CircleQuestionMark,
  ClipboardList,
  ClipboardPaste,
  Clock3,
  Coins,
  Copy,
  Cpu,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  FlaskConical,
  Globe2,
  Image,
  Key,
  KeyRound,
  Gauge,
  ListFilter,
  Loader2,
  LoaderCircle,
  Menu,
  MessageSquareText,
  Pencil,
  Pin,
  PinOff,
  Play,
  Plus,
  Power,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Search,
  Settings,
  ShieldCheck,
  Square,
  Trash2,
  TrendingUp,
  TriangleAlert,
  User,
  UserPlus,
  Wrench,
  X,
} from "lucide-vue-next";

defineOptions({ inheritAttrs: false });

const props = defineProps<{
  name: string;
}>();

const icons: Record<string, Component> = {
  "i-lucide-activity": Activity,
  "i-lucide-arrow-down": ArrowDown,
  "i-lucide-arrow-left": ArrowLeft,
  "i-lucide-arrow-right": ArrowRight,
  "i-lucide-arrow-up": ArrowUp,
  "i-lucide-bar-chart-3": BarChart3,
  "i-lucide-book-open": BookOpen,
  "i-lucide-bot": Bot,
  "i-lucide-brain": Brain,
  "i-lucide-calendar": Calendar,
  "i-lucide-check": Check,
  "i-lucide-check-circle": CheckCircle,
  "i-lucide-chevron-down": ChevronDown,
  "i-lucide-chevron-left": ChevronLeft,
  "i-lucide-chevron-right": ChevronRight,
  "i-lucide-chevron-up": ChevronUp,
  "i-lucide-circle-alert": CircleAlert,
  "i-lucide-alert-circle": CircleAlert,
  "i-lucide-circle-dashed": CircleDashed,
  "i-lucide-circle-question-mark": CircleQuestionMark,
  "i-lucide-clipboard-list": ClipboardList,
  "i-lucide-clipboard-paste": ClipboardPaste,
  "i-lucide-clock-3": Clock3,
  "i-lucide-coins": Coins,
  "i-lucide-copy": Copy,
  "i-lucide-cpu": Cpu,
  "i-lucide-external-link": ExternalLink,
  "i-lucide-eye": Eye,
  "i-lucide-eye-off": EyeOff,
  "i-lucide-file-text": FileText,
  "i-lucide-flask-conical": FlaskConical,
  "i-lucide-globe-2": Globe2,
  "i-lucide-image": Image,
  "i-lucide-key": Key,
  "i-lucide-key-round": KeyRound,
  "i-lucide-gauge": Gauge,
  "i-lucide-list-filter": ListFilter,
  "i-lucide-loader-2": Loader2,
  "i-lucide-loader-circle": LoaderCircle,
  "i-lucide-menu": Menu,
  "i-lucide-message-square-text": MessageSquareText,
  "i-lucide-pencil": Pencil,
  "i-lucide-pin": Pin,
  "i-lucide-pin-off": PinOff,
  "i-lucide-play": Play,
  "i-lucide-plus": Plus,
  "i-lucide-power": Power,
  "i-lucide-refresh-cw": RefreshCw,
  "i-lucide-rotate-ccw": RotateCcw,
  "i-lucide-rotate-cw": RotateCw,
  "i-lucide-search": Search,
  "i-lucide-settings": Settings,
  "i-lucide-shield-check": ShieldCheck,
  "i-lucide-square": Square,
  "i-lucide-trash-2": Trash2,
  "i-lucide-trending-up": TrendingUp,
  "i-lucide-triangle-alert": TriangleAlert,
  "i-lucide-user": User,
  "i-lucide-user-plus": UserPlus,
  "i-lucide-wrench": Wrench,
  "i-lucide-x": X,
};

const icon = computed(() => icons[props.name] ?? CircleDashed);
</script>

<template>
  <component :is="icon" aria-hidden="true" v-bind="$attrs" />
</template>
