[limit]
context = 128_000
output = 4_096

[modalities]
input = ["text"]
output = ["text"]

[opendum]
providers = ["nvidia_nim"]
aliases = ["google-codegemma-7b", "google/codegemma-7b"]
ignored = true

[opendum.upstream]
nvidia_nim = "google/codegemma-7b"
