[limit]
context = 128_000
output = 4_096

[modalities]
input = ["text","image"]
output = ["text"]

[opendum]
providers = ["nvidia_nim"]
aliases = ["google-gemma-3-1b-it", "google/gemma-3-1b-it"]
ignored = true

[opendum.upstream]
nvidia_nim = "google/gemma-3-1b-it"
