// OpenRouter API constants

export const OPENROUTER_API_BASE_URL = "https://openrouter.ai/api/v1";

export const OPENROUTER_SUPPORTED_PARAMS = new Set([
  "model",
  "messages",
  "temperature",
  "top_p",
  "max_tokens",
  "max_completion_tokens",
  "stream",
  "stream_options",
  "tools",
  "tool_choice",
  "presence_penalty",
  "frequency_penalty",
  "n",
  "stop",
  "seed",
  "response_format",
  "reasoning",
  "reasoning_effort",
]);

export const OPENROUTER_MODEL_MAP: Record<string, string> = {
  "aurora-alpha": "openrouter/aurora-alpha",
  "deepseek-r1-0528": "deepseek/deepseek-r1-0528:free",
  "dolphin-mistral-24b-venice-edition": "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
  "gemma-3-12b-it": "google/gemma-3-12b-it:free",
  "gemma-3-27b-it": "google/gemma-3-27b-it:free",
  "gemma-3-4b-it": "google/gemma-3-4b-it:free",
  "gemma-3n-e2b-it": "google/gemma-3n-e2b-it:free",
  "gemma-3n-e4b-it": "google/gemma-3n-e4b-it:free",
  "glm-4.5-air": "z-ai/glm-4.5-air:free",
  "gpt-oss-120b": "openai/gpt-oss-120b:free",
  "gpt-oss-20b": "openai/gpt-oss-20b:free",
  "hermes-3-llama-3.1-405b": "nousresearch/hermes-3-llama-3.1-405b:free",
  "lfm-2.5-1.2b-instruct": "liquid/lfm-2.5-1.2b-instruct:free",
  "lfm-2.5-1.2b-thinking": "liquid/lfm-2.5-1.2b-thinking:free",
  "llama-3.2-3b-instruct": "meta-llama/llama-3.2-3b-instruct:free",
  "llama-3.3-70b-instruct": "meta-llama/llama-3.3-70b-instruct:free",
  "mistral-small-3.1-24b-instruct": "mistralai/mistral-small-3.1-24b-instruct:free",
  "nemotron-3-nano-30b-a3b": "nvidia/nemotron-3-nano-30b-a3b:free",
  "nemotron-nano-12b-v2-vl": "nvidia/nemotron-nano-12b-v2-vl:free",
  "nemotron-nano-9b-v2": "nvidia/nemotron-nano-9b-v2:free",
  "openrouter-free": "openrouter/free",
  "qwen3-235b-a22b-thinking-2507": "qwen/qwen3-235b-a22b-thinking-2507",
  "qwen3-4b": "qwen/qwen3-4b:free",
  "qwen3-coder": "qwen/qwen3-coder:free",
  "qwen3-next-80b-a3b-instruct": "qwen/qwen3-next-80b-a3b-instruct:free",
  "qwen3-vl-235b-a22b-thinking": "qwen/qwen3-vl-235b-a22b-thinking",
  "qwen3-vl-30b-a3b-thinking": "qwen/qwen3-vl-30b-a3b-thinking",
  "solar-pro-3": "upstage/solar-pro-3:free",
  "step-3.5-flash": "stepfun/step-3.5-flash:free",
  "trinity-large-preview": "arcee-ai/trinity-large-preview:free",
  "trinity-mini": "arcee-ai/trinity-mini:free",
};

export const OPENROUTER_MODELS = new Set(Object.keys(OPENROUTER_MODEL_MAP));
