// OpenRouter API constants

export const OPENROUTER_API_BASE_URL = "https://openrouter.ai/api/v1";

export const OPENROUTER_SUPPORTED_PARAMS = new Set([
  "model",
  "messages",
  "temperature",
  "top_p",
  "max_tokens",
  "max_completion_tokens",
  "stream",
  "stream_options",
  "tools",
  "tool_choice",
  "presence_penalty",
  "frequency_penalty",
  "n",
  "stop",
  "seed",
  "response_format",
  "reasoning",
  "reasoning_effort",
]);

export const OPENROUTER_MODEL_MAP: Record<string, string> = {
  "arcee-ai-trinity-large-preview": "arcee-ai/trinity-large-preview:free",
  "arcee-ai-trinity-mini": "arcee-ai/trinity-mini:free",
  "cognitivecomputations-dolphin-mistral-24b-venice-edition": "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
  "deepseek-deepseek-r1-0528": "deepseek/deepseek-r1-0528:free",
  "google-gemma-3-12b-it": "google/gemma-3-12b-it:free",
  "google-gemma-3-27b-it": "google/gemma-3-27b-it:free",
  "google-gemma-3-4b-it": "google/gemma-3-4b-it:free",
  "google-gemma-3n-e2b-it": "google/gemma-3n-e2b-it:free",
  "google-gemma-3n-e4b-it": "google/gemma-3n-e4b-it:free",
  "liquid-lfm-2.5-1.2b-instruct": "liquid/lfm-2.5-1.2b-instruct:free",
  "liquid-lfm-2.5-1.2b-thinking": "liquid/lfm-2.5-1.2b-thinking:free",
  "meta-llama-llama-3.2-3b-instruct": "meta-llama/llama-3.2-3b-instruct:free",
  "meta-llama-llama-3.3-70b-instruct": "meta-llama/llama-3.3-70b-instruct:free",
  "mistralai-mistral-small-3.1-24b-instruct": "mistralai/mistral-small-3.1-24b-instruct:free",
  "nousresearch-hermes-3-llama-3.1-405b": "nousresearch/hermes-3-llama-3.1-405b:free",
  "nvidia-nemotron-3-nano-30b-a3b": "nvidia/nemotron-3-nano-30b-a3b:free",
  "nvidia-nemotron-nano-12b-v2-vl": "nvidia/nemotron-nano-12b-v2-vl:free",
  "nvidia-nemotron-nano-9b-v2": "nvidia/nemotron-nano-9b-v2:free",
  "openai-gpt-oss-120b": "openai/gpt-oss-120b:free",
  "openai-gpt-oss-20b": "openai/gpt-oss-20b:free",
  "openrouter-aurora-alpha": "openrouter/aurora-alpha",
  "openrouter-free": "openrouter/free",
  "qwen-qwen3-4b": "qwen/qwen3-4b:free",
  "qwen-qwen3-coder": "qwen/qwen3-coder:free",
  "qwen-qwen3-next-80b-a3b-instruct": "qwen/qwen3-next-80b-a3b-instruct:free",
  "qwen-qwen3-vl-235b-a22b-thinking": "qwen/qwen3-vl-235b-a22b-thinking",
  "qwen-qwen3-vl-30b-a3b-thinking": "qwen/qwen3-vl-30b-a3b-thinking",
  "stepfun-step-3.5-flash": "stepfun/step-3.5-flash:free",
  "tngtech-deepseek-r1t-chimera": "tngtech/deepseek-r1t-chimera:free",
  "tngtech-deepseek-r1t2-chimera": "tngtech/deepseek-r1t2-chimera:free",
  "tngtech-tng-r1t-chimera": "tngtech/tng-r1t-chimera:free",
  "upstage-solar-pro-3": "upstage/solar-pro-3:free",
  "z-ai-glm-4.5-air": "z-ai/glm-4.5-air:free",
};

export const OPENROUTER_MODELS = new Set(Object.keys(OPENROUTER_MODEL_MAP));
